language: python

sudo: true

os: linux

python:
    - "3.5"

matrix:
  allow_failures:
    - python: "3.5"

before_install:
  - sudo chmod u+x .travis/*.sh
  - /bin/bash .travis/setup.sh &>/dev/null
  #- wget -O gdrive https://drive.google.com/uc\?id\=1Ej8VgsW5RgK66Btb9p74tSdHMH3p4UNb\&export\=download
  #- chmod +x gdrive
  #- echo "4/ewEhDzS3KF59BK_90lJ8AljUaloXp-2-g7HCuXOMjAG9mNm868R7hFk" | ./gdrive about

script:
                               # recipe
  - /bin/bash .travis/build.sh Singularity

                               # recipe with tag
  #- /bin/bash .travis/build.sh --tag sneeze Singularity.tag

  # Examples with upload to storage clients defined by sregistry
  # https://singularityhub.github.io/sregistry-cli/clients
  # Environment variables must be defined in CI encrypted secrets/settings

  #- /bin/bash .travis/build.sh --uri collection/container --tag tacos --cli google-storage Singularity
  #- /bin/bash .travis/build.sh --uri collection/container --cli google-drive Singularity
  #- /bin/bash .travis/build.sh --uri collection/container --cli globus Singularity
  #- /bin/bash .travis/build.sh --uri collection/container --cli registry Singularity

after_script:
  # - ./gdrive upload Singularity.simg
  - echo "Done"
  
